### ISSUE TITLE
Find date for Q1 2021 meeting

### ISSUE THREAD

**Issue by christianvdorrien** [ices-eg/wg_WGSFDGOV#11]
Dear @ices-eg/wgsfdgov ,

please indicate [here ](https://terminplaner4.dfn.de/xC2TIrrSRBnDnLUN) the days where you would be available to have our Q1 meeting in 2021. Start time: 14:00

Thanks, Christian

**Comment by christianvdorrien** [comment]
Hi @colinpmillar @cmspinto @neilcampbelll @roimartins @LaraSalvany  , just a short reminder to fill out the doodle for our next WGSFDGOV meeting. Thanks, Christian

**Comment by christianvdorrien** [comment]
@colinpmillar @cmspinto  @roimartins @LaraSalvany here's the plain link, so you don't need to open github: https://terminplaner4.dfn.de/xC2TIrrSRBnDnLUN
Cheers Christian

**Comment by LaraSalvany** [comment]
Done! Thanks Christian

**Comment by christianvdorrien** [comment]
Good morning, @ices-eg/wgsfdgov , we found a date: 25. February 2021, at 14:00. I'll prepare the agenda, if you have items, please send them in. Cheers, Christian
