### ISSUE TITLE
Review of draft data flow schematic: ICES VMS-Logbook

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/wg_WGSFDGOV#2]
You are probably aware that we are in the process of being evaluated for accreditation as a Data Centre as part of the overall quality assurance efforts for ICES advice. One of the things that we have started addressing are the descriptions of the dataflows into ICES, and the resultant data products/advice. This is now being produced as a publication series ‘ICES Data Flow Schematics’ and the first one has been published (and at least Neil C commented on this one)

[NEAF VMS Data Flow](http://ices.dk/sites/pub/Publication%20Reports/Data%20Visualization/ICES%20Data%20Flow%20Schematics_No.1-VMS-NEAFC.pdf )

For a description of the overall publication process, which has been approved by ACOM, see [text here](http://community.ices.dk/Publications/dataflows/_layouts/15/start.aspx#/SitePages/HomePage.aspx )

-------------------------------------- 
We are now in the process of working through the main VMS-Logbook data flow, which is of course heavily tied to WGSFD and WGSFDGOV. The folder and the pdf of the draft schematic are on links below. We would like you to take a look and provide any suggestions/edits as comments on the pdf directly, or by email/other document if that is easier. Joana, in copy, is responsible for updating the schematic, and so please ask her if there are any things that are not clear in the diagram. 

We aim to have a final publication of this data flow for November 2020, so we would appreciate feedback by the 1st October. 

Many thanks for your help with this

[DataFlow Publications Staging Folder](http://community.ices.dk/Publications/dataflows/_layouts/15/start.aspx#/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FPublications%2Fdataflows%2FShared%20Documents%2F2%2E%202020%2DVMS%2DICES&FolderCTID=0x0120002B6BCCEF5C6CC14896CD3A12572762DA&View=%7B930F668A%2D6049%2D478F%2DB0F9%2D0FAA15AA1C01%7D)

[DataFlowVMS.pdf](http://community.ices.dk/Publications/dataflows/Shared%20Documents/2.%202020-VMS-ICES/DataFlowVMS.pdf)

**Comment by neil-ices-dk** [comment]
@christianvdorrien and @neilcampbelll at the upcoming ad-hoc meeting of WGSFDGOV, will you be able to spend 10-15 minutes on this? thanks, Neil

**Comment by christianvdorrien** [comment]
Hi Neil, good idea - let's do that. Cheers Christian

**Comment by LaraSalvany** [comment]
Minor comments only
In **Data products**: _The aggregated spatial data are approved by the WGSFD subgroup and described in their report_ the aggregated products are not published in the group report.
In **Advice: 
-what's the footnote 1? 
-The other type of advice products, the technical services (no peer-review nor ADG) should also be included.

**Comment by neil-ices-dk** [comment]
data products (to change text to below):
_Aggregated data are not compliant with the quality requirements and one or more data depositors are asked for clarification and/or to resubmit their data_

_The work of WGSFD is reviewed by the review group_ change to:
The outputs (products, reports, maps etc.) of WGSFD are reviewed by the review group

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/96453719-2b9c1b80-121b-11eb-885f-6d273008071e.png)

we need to reflect better that it can be a) kicked back to the WG or b) annotated as a caveat in the advice

**Comment by neil-ices-dk** [comment]
> -The other type of advice products, the technical services (no peer-review nor ADG) should also be included.

agree :)

**Comment by neil-ices-dk** [comment]
@pcrjoana welcome to the thread - and the above comments are for you to take into account; please post a follow-up here once you have a new version of the dataflow ready :)

**Comment by pcrjoana** [comment]
Hello all! I am sorry for taking so long to implement your comments. The data flow schematic as now been updated and can be found at: http://community.ices.dk/Publications/dataflows/_layouts/15/start.aspx#/SitePages/HomePage.aspx?RootFolder=%2FPublications%2Fdataflows%2FShared%20Documents%2F2%2E%202020%2DVMS%2DICES&FolderCTID=0x0120002B6BCCEF5C6CC14896CD3A12572762DA&View=%7BB4F7E007%2D8185%2D4F33%2D85CB%2DEEF407BA4A8E%7D
@LaraSalvany the footnote refers to a table listing the different types of recurring advice. The table is in the file VMSadvice, which can also be found in the folder linked above.

**Comment by neil-ices-dk** [comment]
@christianvdorrien and @neilcampbelll any further thoughts on the revised data flow, we're keen to progress this one :)

**Comment by christianvdorrien** [comment]
Thanks Joana and Neil for the update, and sorry for the late reply (I thought this is already closed): 
I think it looks fine! My only comment concerns the footnote-numbers - do these point to the table in the word-doc?
Cheers Christian

**Comment by neil-ices-dk** [comment]
thanks @christianvdorrien, see Joana's earlier comment about the footnotes, hope that answers it 🧑‍🔧 

> @LaraSalvany the footnote refers to a table listing the different types of recurring advice. The table is in the file VMSadvice, which can also be found in the folder linked above.

**Comment by christianvdorrien** [comment]
ah, these modern techniques seem to me to become more and more conspicuous ;-)
