### ISSUE TITLE
To Dos for DataCall 2022

### ISSUE THREAD

**Issue by christianvdorrien** [ices-eg/wg_WGSFDGOV#22]
see ToDo list [here ](https://docs.google.com/document/d/1rnsdTgmphlmQa3YU8wxkh046MfoVUDfWE3diasrnHUs/edit#)

List will be filled/updated at Q3 meeting

**Comment by neil-ices-dk** [comment]
@christianvdorrien and @LaraSalvany in the to-do's we are missing the publication of the new VMS licence. I'm just looking at it now and i need an ok on an addition that was omitted from the VMS one but it is in the other restricted data licences:

point C below is to cover the situation that arises when a legitimate request from a party asks directly to countries for access to the ICES VMS dataset, which can be independent of an ICES group and outside of a data call request from inception. We have quite a few examples of this scenario if you need more info.

### License Grant

Full access to use restricted data are granted to the following:
a)	an ICES group with related Advice terms of reference;
b)	an ICES advice requestor, where data have been provisioned under a data call from the ICES advice requestor;
**c)	Anyone given a direct grant of rights by the Licensor(s)**

**Comment by LaraSalvany** [comment]
Thanks Neil, I had it on my agenda for tomorrow but not in the project board.
On point c), I understand it is it like the WGCRAN request we get every year? We/ICES would still coordinate the data request and all, correct?

Thanks,
Lara

**Comment by christianvdorrien** [comment]
Thanks Neil, I see your point and as long as all affected Licensors/countries accepted the request for access than it should be no problem. 

Until tomorrow, 
Christian

**Comment by neil-ices-dk** [comment]
> Thanks Neil, I had it on my agenda for tomorrow but not in the project board. On point c), I understand it is it like the WGCRAN request we get every year? We/ICES would still coordinate the data request and all, correct?
> 
> Thanks, Lara

Hi Lara - i was thinking of requests from countries i.e. UK, Norway and DK where they have asked for access to the dataset for a national project such as økomar (ecomar) from DK

**Comment by neil-ices-dk** [comment]
> Thanks Neil, I see your point and as long as all affected Licensors/countries accepted the request for access than it should be no problem.
> 
> Until tomorrow, Christian

thanks Christian, yes - that has been the practice until now, and this is ensuring the license covers that use
