### ISSUE TITLE
Agenda meeting Q4 10.12.2020 14:00

### ISSUE THREAD

**Issue by christianvdorrien** [ices-eg/wg_WGSFDGOV#7]
Dear all, 

please find below the topics for our next meeting in the coming week, using the github project board (hope it will work 😉). 

1. Manifesto 
2. Potential anonymity issues in the special request from OSPAR to update VMS layers
3. Contribution to Science Highlights to promote DSTSG  (deadline 18.12.2020)
4. **NEW:** e-report 2020 finalization
4. News from the Data Center
5. Any other business 
    1.  No recommendations from other EGs (so far)
    1. Date of next meeting

Where relevant, I will also add these topics as issues to the project board, together with more infos/documents. Hopefully this can help to organize our work even better. 

If you do have additional topics, either add them via the project board or e-mail them to me. 

See you next week!
Cheers
Christian

**Comment by christianvdorrien** [comment]
@ices-eg/wgsfdgov   @roimartins Dear All, I just created the agenda for our upcoming meeting on the github project board. I do hope that this will be no double notification, but I am not sure whether you all got the related e-mail. Have a nice weekend, Cheers Christian

**Comment by jensr** [comment]
Thanks  @christianvdorrien got the emails, and look forward to meeting

**Comment by neil-ices-dk** [comment]
> 
1. [Manifesto](https://docs.google.com/document/d/1gjZrM27fHSE67ocMYQwMQT0_3VRe2ySjHV87vv1OtiM/edit?usp=sharing)
@neilcampbelll to finalize SCOPE
@lenaszymanek to finalize ORGANISATION also refer to [Guidance for ICES Groups](http://www.ices.dk/about-ICES/Documents/Guidelines_for_ICES_Groups.pdf)
@jensr and @neilcampbelll and @neil-ices-dk for ORGANISATIONAL DEPENDENCIES
@jensr to review and finalize METADATA AND PUBLISHING
@christianvdorrien with input from @neil-ices-dk and @neilcampbelll  to review INTERPRETATION and PRIORITISATION
@christianvdorrien to author new section on GUIDANCE and TRAINING
@roimartins and @christianvdorrien to provide some detail on EG side of DEFINITION OF RESOURCES AVAILABLE
@colinpmillar to have a final edit of RESPONSIBILITIES

**All updates ahead of 20th January, when we will have  finalisation meeting**

> 
>     2. Potential anonymity issues in the special request from OSPAR to update VMS layers
> 
>     3. Contribution to Science Highlights to promote DSTSG  (deadline 18.12.2020)
> 
>     4. **NEW:** e-report 2020 finalization
> 
>     5. News from the Data Center
> 
>     6. Any other business
>        
>        1. No recommendations from other EGs (so far)
>        2. Date of next meeting
>        3. HELCOM BLUES project will require a VMS/LB product from ICES in 2022
>

**Comment by LaraSalvany** [comment]
**2. Potential anonymity issues in the special request from OSPAR to update VMS layers**
Technical aspects should be discussed at WGSFD. The scope of WGSFDGOV is to discuss whether criteria and processes are documented and follow the data policy.
WGSFDGOV suggests that a subgroup of WGSFD experts will work intersessionally (starting February 2021) on best approaches to represent sensitive data. 
@roimartins will set a doodle and gauge interest among WGSFD members
@colinpmillar will prepare data for subgroup work
@LaraSalvany will inform OSPAR Sec about anonymity issues and present them with options on how to represent the data
 
next meeting 20 January 2021

**Comment by colinpmillar** [comment]
Hi @LaraSalvany @roimartins @neilcampbelll and @christianvdorrien,
I can try and get this (https://github.com/ices-eg/wg_WGSFDGOV/issues/7#issuecomment-742580087) done before the end of the year. I will base it on the 2020 submissions because the 2019 submission did not have the vessel ID column and there is no point in developing alternative procedures when we will not use them.  

See this issue for the discussion on the anonymity report: https://github.com/ices-eg/wg_WGSFDGOV/issues/6

**Comment by christianvdorrien** [comment]
Dear @ices-eg/wgsfdgov , 

thank you for a good meeting, where we made good progress on the two most important issues. Regarding the two other still open issues, I will ask for your input by making comments on the github. 

I wish you a relaxing and healthy Christmas🎄 in the (hopefully as large as possible) circle of your families and all the best for the new year - it can only get better ... 😊

Best wishes
Christian

**Comment by christianvdorrien** [comment]
Hi @colinpmillar,
cc @LaraSalvany @roimartins @neilcampbelll

 >  I will base it on the 2020 submissions because the 2019 submission did not have the vessel ID column and there is no point in developing alternative procedures when we will not use them.

I fully agree!
