### ISSUE TITLE
Finalize the Manifesto

### ISSUE THREAD

**Issue by christianvdorrien** [ices-eg/wg_WGSFDGOV#8]
We developed the Manifesto further, but some parts still need editing and finalization. 

Here is the link to the Google Docs version: 
https://docs.google.com/document/d/1gjZrM27fHSE67ocMYQwMQT0_3VRe2ySjHV87vv1OtiM/edit?usp=sharing

It would be great if we could finish this manifesto by the beginning of next year at the latest. .

**Comment by christianvdorrien** [comment]
@roimartins Hi Roi, thanks for your additions and comments, to that I answered. If you are happy with this, let me know. Then I can forward the Manifesto to Jens. 
Cheers, Christian

**Comment by roimartins** [comment]
Thanks @christianvdorrien , i am happy with it .
