### ISSUE TITLE
write e-report 2020

### ISSUE THREAD

**Issue by christianvdorrien** [ices-eg/wg_WGSFDGOV#9]
@ices-eg/wgsfdgov 
Dear All, 
here's a link to the first draft of our e-evaluation for 2020:
[2020_HAPISG_WGSFDGOV_interim_cvd.docx](https://github.com/ices-eg/wg_WGSFDGOV/files/5667613/2020_HAPISG_WGSFDGOV_interim_cvd.docx)

Please read and edit as needed, so that we can try to finalize this at our meeting. 

Thanks & cheers
Christian

**Comment by christianvdorrien** [comment]
Dear @ices-eg/wgsfdgov , 

could you please read the draft for the e-evaluation doc ([2020_HAPISG_WGSFDGOV_interim_cvd.docx](https://github.com/ices-eg/wg_WGSFDGOV/files/5667613/2020_HAPISG_WGSFDGOV_interim_cvd.docx)) and either reply that it is o.k. or amend/correct where necessary. 

Many thanks!
Christian

**Comment by jensr** [comment]
@christianvdorrien I took a look at the evaluation.  Overall it is fine (and obviously this should help so there's no surprises from me reviewing it after submission :-) )
I think it is worth mentioning that the github environment has been established now - this progress on tor B. It might not be the fully fledged mechanism, but it provides the platform for organizing the priorities as the next step? 
It might also be worth putting a note in the science highlight section about the highlight/submission for the DSTSG launch. 

Hope this is helpful.

**Comment by christianvdorrien** [comment]
Dear @ices-eg/wgsfdgov, see [here ](https://github.com/ices-eg/wg_WGSFDGOV/files/5716450/2020_HAPISG_WGSFDGOV_interim_201218.docx ) the e-evaluation doc, that I sent to Karolina today. 

I would like to use this chance to thank you all very much for all your contributions during our first year of WGSFDGOV! I think we've already made quite a bit of progress, and I look forward to continuing our collective efforts in the coming year.

Now I would like to wish you a well-deserved break 📴, a Merry Christmas 🎄 and all the best for the New Year🍀,
Christian

**Comment by neil-ices-dk** [comment]
likewise @christianvdorrien have a good Christmas and keep on keeping on 🎅
